sudo: false
language: node_js
node_js:
  - 9

script:
  - npm run build-prd

after_success: 
  - cd ./dist
  - git init
  - git config user.name "coldxu"
  - git config user.email "coldxuweb@163.com"
  - git add .
  - git commit -m "Update website"
  - git push --force --quiet "https://${GH_REF}?private_token=6421ad9e080f5e437b33cd24802725d7a266811aeff4025d48ff1652f9fc2a7b" master:master

branches:
  only:
  - master

env:
 global:
   - GH_REF: gitee.com/coldxuweb-dist/h-blog
