sudo: false
language: node_js
node_js:
  - 9

script:
  - npm run build-prd

after_success: 
  - cd ./dist
  - git init
  - git config user.name "coldxu"
  - git config user.email "coldxuweb@163.com"
  - git add .
  - git commit -m "Update website"
  - git push --force --quiet "https://ColdXu:${CODING_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master
env:
 global:
   - GH_REF: git.coding.net/ColdXu/dist-hblog.git   
