sudo: false
language: node_js
node_js:
  - 9

script:
  - npm run build-prd

after_success: 
  - cd ./dist
  - git init
  - git config user.name "coldxu"
  - git config user.email "coldxuweb@163.com"
  - git add .
  - git commit -m "Update website"
  - git push --force --quiet "https://${GH_REF}?private_token=zTdYq2SvPfPxxt3yffr4" master:master

branches:
  only:
  - master

env:
 global:
   - GH_REF: gitee.com/coldxuweb-dist/h-blog
